baseurl: "https://pycon.id/"
title: "PyCon Indonesia 2018"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-34348403-11"

params:
  # Conference info
  Name: "PyCon Indonesia 2018"
  Description: "PyCon Indonesia is a conference where Python users, or people interested in Python, gather to learn from each other and meet other members of the community. We hope that everyone joining PyCon ID will not only learn new and exciting things, but also meet new friends and strengthen the connection with the community, and thus the community itself. This year, we chose 'Python for Everyone' as our theme. The Pycon ID staff is continuing to work hard on making a conference that will allow everyone to have a great time and unlock new possibilities through Python."
  Date: "November 3-4"
  # Price: "" # If your event is free, just comment this line
  Venue: "Kalbis Institute"
  Address: "Jl. Pulomas Selatan kav.22, Jakarta Timur 13210"
  City:  "Jakarta"
  State: "Indonesia"
  Images: ["/img/cover.jpg"]
  # GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - cfp
    # - location
    # - speakers
    # - schedule
    # - code-of-conduct
    - sponsors
    - partners
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    cfp: "Call for Paper"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"
    call-for-paper: "Speak at Pycon ID"
    blog: "Blog"
    code-of-conduct: "Code of Conduct"
    sponsors: "Sponsors"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
<<<<<<< HEAD
    text: "Register now!"
    link: "https://tiket.pycon.id"
=======
    text: "Get your ticket!"
    link: "https://tiket.pycon.id/"
>>>>>>> af43d9f5618171c69dd5058896bd8d04d032f772

  # List of Sponsors
  Sponsors:
    Venue:
      - name: "Kalbis Institute"
        logo: "/img/kalbis.png"
        url: "http://kalbis.ac.id/"
    Diamond:

    Platinum:
      - name: "Cloud Kilat"
        logo: "/img/cloudkilat.png"
        url: "https://www.cloudkilat.com/"
      - name: "Python Software Foundation"
        logo: "/img/psf.png"
        url: "https://www.python.org/psf/"
    Gold:

    Silver:
      - name: "Jetbrains"
        logo: "/img/jetbrains.svg"
        url: "https://www.jetbrains.com/"
      - name: "Jublia"
        logo: "/img/jublia.png"
        url: "https://jublia.com/"

  # List of Partners
  Partners:
    - name: "Python Indonesia"
      logo: "/img/id-python-logo_400x400.png"
      url: "https://python.or.id"

  # The entire schedule
  Schedule:
    first:
      - name: "Open Registration"
        time: "8h00"

      - name: "Opening Speech"
        time: "9h00"

      - name: "Keynote 1"
        time: "9h30"

      - name: "Session 1"
        time: "10h10"

      - name: "Coffee Break 1"
        time: "11h00"

      - name: "Session 2"
        time: "11h20"

      - name: "Session 3"
        time: "12h00"

      - name: "Lunch"
        time: "12h35"

      - name: "Session 4"
        time: "13h40"

      - name: "Session 5"
        time: "14h20"

      - name: "Session 6"
        time: "15h00"

      - name: "Coffee Break 2"
        time: "15h35"

      - name: "Session 7"
        time: "15h55"

      - name: "Lightning Talk"
        time: "16h35"

      - name: "Closing"
        time: "17h10"

    second:
      - name: "Open Registration"
        time: "8h30"

      - name: "Keynote 2"
        time: "9h30"

      - name: "Session 1"
        time: "10h10"

      - name: "Coffee Break 1"
        time: "11h00"

      - name: "Session 2"
        time: "11h20"

      - name: "Session 3"
        time: "12h00"

      - name: "Lunch"
        time: "12h35"

      - name: "Session 4"
        time: "13h40"

      - name: "Session 5"
        time: "14h20"

      - name: "Session 6"
        time: "15h00"

      - name: "Coffee Break 2"
        time: "15h35"

      - name: "Session 7"
        time: "15h55"

      - name: "Lightning Talk"
        time: "16h35"

      - name: "Closing"
        time: "17h10"
